# Generated by Django 3.0.7 on 2020-06-30 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 30, 22, 17, 1, 191715), verbose_name='date published'),
        ),
    ]
